pipeline:
  identifier: Build_moemirza14_go_pipeline_sample_1741893663442
  name: Build go-pipeline-samplex1
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1729368749309
        repoName: moemirza14/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: run unit tests
                  identifier: run_unit_tests
                  spec:
                    connectorRef: <+input>
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                      exit 0
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
                  description: run_unit_tests
              - step:
                  type: Run
                  name: go build
                  identifier: go_build
                  spec:
                    connectorRef: <+input>
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                      exit 0
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build And Push Docker Registry
                  identifier: Build_And_Push_Docker_Registry
                  spec:
                    connectorRef: MoeCon
                    repo: moemirza12/gotestx1
                    tags:
                      - <+pipeline.sequenceId>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
  tags: {}
